### ISSUE TITLE
Errors when running Quick Start

### ISSUE THREAD

**Issue by unclebuff** [MichiganCOG/devil#3]
Hi, It's me again.
When I did a test following Quick Start, some errors poped up.

After runs `python submit-evaluate-inpainting.py cpnet flickr-all fvi-fgd-h -m local`
I got "Mean lpips = 4035.5187175428873
Mean pcons_psnr_mask = 40.32757932735643
Mean psnr = 36.62060644992114
Mean ssim = 0.9807143613543343
2022-02-25 17:47:55.506379
Run time was 42.42 minutes
The processes for some metrics failed: warp_error_mask, vfid_clips, vfid, pvcs
Evaluation failed. Printing execution log:......"
and it ends with “CalledProcessError: Command '['bash', '/home/liguanxiao/inpainting/devil/slurm/evaluate-inpainting.sh']' returned non-zero exit status 4.”
And similar error came up when I runs `python submit-evaluate-inpainting.py cpnet flickr-all fvi-fgd-h -m local -a ::include fid ::update`
except the log ends with "returned non-zero exit status 1."

Apart from that, when I execute the final command `./scripts/print-quant-results-table.sh`
error says "devil/video-inpainting-evaluation/src/main/summarize_quant_results.py", line 76, in add_summary
    if metric_values.size > 1:
AttributeError: 'NoneType' object has no attribute 'size'"

I really appreciate it if you can help me and answer these questions, thanks.

**Comment by rszeto** [comment]
Hi,

`print-quant-results-table.sh` will not work unless the `submit-evaluate-inpainting.py` you posted complete successfully.

Would it be possible for you to attach a more complete error log? Unfortunately `CalledProcessError` is not particularly informative; it only indicates that some error occurred within the `evaluate-inpainting.sh` script.

**Comment by unclebuff** [comment]
Hi, I solve the first bug by using older version GPU. 
`python submit-evaluate-inpainting.py cpnet flickr-all fvi-fgd-h -m local -a ::include fid ::update` works great now.
However, when I run `./scripts/print-quant-results-table.sh` error still comes up and says 

Traceback (most recent call last):
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/src/main/summarize_quant_results.py", line 113, in <module>
    main(**vars(args))
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/src/main/summarize_quant_results.py", line 43, in main
    add_summary(table, result_path, no_se, table_headers, show_list)
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/src/main/summarize_quant_results.py", line 75, in add_summary
    if metric_values.size > 1:
AttributeError: 'NoneType' object has no attribute 'size'

Can you help me out of it?

**Comment by rszeto** [comment]
Can you send me the output of the following command when you use the old and the new GPUs? This might be a support issue that needs addressing.

```bash
nvidia-smi --format=csv --query-gpu=gpu_name,driver_version
```

As for the `summarize_quant_results.py` error, you will need to re-run BOTH `submit-evaluate-inpainting.py` commands, not just the FID one you posted, since both of them failed earlier. I would also recommend moving or deleting the `.npz` that got generated from the `submit-evaluate-inpainting.py` to make sure it's in an expected state.

**Comment by unclebuff** [comment]
> name, driver_version
TITAN RTX, 450.57
TITAN RTX, 450.57

> name, driver_version
NVIDIA GeForce RTX 3090, 470.103.01
NVIDIA GeForce RTX 3090, 470.103.01
NVIDIA GeForce RTX 3090, 470.103.01
NVIDIA GeForce RTX 3090, 470.103.01

Devil works great on titan RTX following your guide
And I'm pretty sure errors on RTX3090 result from inappropriate pytorch version. Since the error returns

> GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.

it should be fixed by using the latest pytorch and cuda

About the previous question I did not express correctly. 
I retest the code and `python submit-evaluate-inpainting.py cpnet flickr-all fvi-fgd-h -m local` works great and outputs

> Mean lpips = 0.0023987161023558555
Mean pcons_psnr_mask = 40.32757932735643
Mean psnr = 36.62060644992114
Mean pvcs = 0.14616594130483768
Mean ssim = 0.9807143613543343
Mean vfid = 0.03665921698741936
Mean vfid_clips = 0.062156595723365626
Mean warp_error_mask = 0.0009567069078109915
2022-03-24 12:12:20.844728
Run time was 64.10 minutes
Removing /tmp/devil-curation-evaluate-inpainting-12195...
Done.

However, when I run the FID one `python submit-evaluate-inpainting.py cpnet flickr-all fvi-fgd-h -m local -a ::include fid ::update
`
error comes up and outputs

> Namespace(eval_feats_root='/home/liguanxiao/inpainting/devil/eval-data/devil/flickr-all', exclude=None, gt_root='/tmp/devil-curation-evaluate-inpainting-29384/dataset', include=['fid'], log_path='/tmp/devil-curation-evaluate-inpainting-29384/output.log', max_num_videos=None, output_path='/home/liguanxiao/inpainting/devil/inpainting-results-quantitative/devil/flickr-all_fvi-fgd-h/cpnet.npz', pred_root='/home/liguanxiao/inpainting/devil/inpainting-results/devil/flickr-all_fvi-fgd-h/cpnet', sim_cons_ps=50, sim_cons_sw=20, update=True)
fid:   0%|                                                                                                                                                                                                                                                                   | 0/150 [02:02<?, ?it/s]
2022-03-24 12:20:48.754009
Run time was 2.04 minutes
The processes for some metrics failed: fid
Evaluation failed. Printing execution log:
/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/site-packages/torchvision/models/inception.py:75: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  warnings.warn('The default weight initialization of inception_v3 will be changed in future releases of '
Downloading: "https://github.com/mseitzer/pytorch-fid/releases/download/fid_weights/pt_inception-2015-12-05-6726825d.pth" to /home/liguanxiao/.cache/torch/hub/checkpoints/pt_inception-2015-12-05-6726825d.pth
Traceback (most recent call last):
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/src/compute_metrics/metric_computer.py", line 25, in run
    self.compute_metric()
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/src/compute_metrics/fid_computer.py", line 18, in compute_metric
    model = InceptionV3([block_idx])
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/src/fid/pytorch_fid/inception.py", line 80, in __init__
    inception = fid_inception_v3()
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/src/fid/pytorch_fid/inception.py", line 188, in fid_inception_v3
    state_dict = load_state_dict_from_url(FID_WEIGHTS_URL, progress=True)
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/site-packages/torch/hub.py", line 481, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/site-packages/torch/hub.py", line 379, in download_url_to_file
    u = urlopen(req)
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/urllib/request.py", line 1354, in do_open
    r = h.getresponse()
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/liguanxiao/inpainting/devil/video-inpainting-evaluation/env/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
Removing /tmp/devil-curation-evaluate-inpainting-29384...
Done.
Traceback (most recent call last):
  File "submit-evaluate-inpainting.py", line 84, in <module>
    main(**vars(args))
  File "submit-evaluate-inpainting.py", line 43, in main
    check_call(['bash', os.path.join(SCRIPT_DIR, 'evaluate-inpainting.sh')], env=env)
  File "/home/liguanxiao/inpainting/devil/env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '/home/liguanxiao/inpainting/devil/slurm/evaluate-inpainting.sh']' returned non-zero exit status 1.

So the `summarize_quant_results.py` error are still there. I hope you can help me out of the FID problem, thanks!

**Comment by rszeto** [comment]
Sorry for the late response. My understanding is that it can't download `FID_WEIGHTS_URL`, which points to `https://github.com/mseitzer/pytorch-fid/releases/download/fid_weights/pt_inception-2015-12-05-6726825d.pth`. Are you able to download that file directly?

**Comment by rszeto** [comment]
Closing due to inactivity.
