### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Fanstering** [MichiganCOG/devil#9]
Hello, this error caused several evaluations to not be executed correctly, which seems to be caused by incorrect loading of pre trained weights. However, I have completed the previous code normally and the weights at the corresponding positions also exist. How can I solve this problem?

Namespace(eval_feats_root='/home/garfield/pyprojects/devil/eval-data/devil/flickr-all', exclude=['fid', 'pcons_psnr', 'pcons_ssim', 'warp_error'], gt_root='/tmp/devil-curation-evaluate-inpainting-27268/dataset', include=None, log_path='/tmp/devil-curation-evaluate-inpainting-27268/output.log', max_num_videos=None, output_path='/home/garfield/pyprojects/devil/inpainting-results-quantitative/devil/flickr-all_fvi-fgd-h/cpnet.npz', pred_root='/home/garfield/pyprojects/devil/inpainting-results/devil/flickr-all_fvi-fgd-h/cpnet', sim_cons_ps=50, sim_cons_sw=20, update=False)
lpips:   0%|                                                                                                                                                                                          | 0/150 [30:06<?, ?it/s]
pcons_psnr_mask: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [30:06<00:00, 12.04s/it]
psnr: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [30:06<00:00, 12.04s/it]
pvcs:   0%|                                                                                                                                                                                           | 0/150 [30:06<?, ?it/s]
ssim: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [30:06<00:00, 12.04s/it]
vfid:   0%|                                                                                                                                                                                           | 0/150 [30:06<?, ?it/s]
vfid_clips:   0%|                                                                                                                                                                                     | 0/150 [30:06<?, ?it/s]
warp_error_mask: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [30:06<00:00, 12.04s/it]
Mean pcons_psnr_mask = 40.32757932735643
Mean psnr = 36.62060644992114
Mean ssim = 0.9807143613543343
Mean warp_error_mask = 0.0009567068571317535
2023-04-17 17:17:55.080326
Run time was 30.11 minutes
The processes for some metrics failed: vfid, pvcs, vfid_clips, lpips
Evaluation failed. Printing execution log:
Traceback (most recent call last):
  File "/home/garfield/pyprojects/devil/video-inpainting-evaluation/src/compute_metrics/metric_computer.py", line 25, in run
    self.compute_metric()
  **File "/home/garfield/pyprojects/devil/video-inpainting-evaluation/src/compute_metrics/vfid_computer.py", line 24, in compute_metric
    weights = torch.load(os.path.join(PROJ_DIR, 'pretrained_models', 'rgb_imagenet.pt'))**
  File "/home/garfield/pyprojects/devil/video-inpainting-evaluation/env/lib/python3.8/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/garfield/pyprojects/devil/video-inpainting-evaluation/env/lib/python3.8/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

#3 It seems that someone has solved this problem by reducing the GPU version. How did this happen?

**Comment by Fanstering** [comment]
![2U643JRI{_W)`FC%UB F``U](https://user-images.githubusercontent.com/62200753/232452720-624e41ca-f851-42dc-8300-f4ac6da5358b.png)
my GPU and driver
